2025-03-14 22:38:12,507 INFO    MainThread:388287 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2025-03-14 22:38:12,508 INFO    MainThread:388287 [wandb_setup.py:_flush():76] Configure stats pid to 388287
2025-03-14 22:38:12,509 INFO    MainThread:388287 [wandb_setup.py:_flush():76] Loading settings from /home/dennis00/.config/wandb/settings
2025-03-14 22:38:12,510 INFO    MainThread:388287 [wandb_setup.py:_flush():76] Loading settings from /home/dennis00/cortexGPT/wandb/settings
2025-03-14 22:38:12,511 INFO    MainThread:388287 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-03-14 22:38:12,512 INFO    MainThread:388287 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-03-14 22:38:12,513 INFO    MainThread:388287 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2025-03-14 22:38:12,514 INFO    MainThread:388287 [wandb_init.py:_log_setup():526] Logging user logs to /home/dennis00/cortexGPT/wandb/run-20250314_223812-ftth0b4x/logs/debug.log
2025-03-14 22:38:12,516 INFO    MainThread:388287 [wandb_init.py:_log_setup():527] Logging internal logs to /home/dennis00/cortexGPT/wandb/run-20250314_223812-ftth0b4x/logs/debug-internal.log
2025-03-14 22:38:12,517 INFO    MainThread:388287 [wandb_init.py:init():566] calling init triggers
2025-03-14 22:38:12,518 INFO    MainThread:388287 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'seed': 0, 'dataset_name': 'ms', 'do_train': True, 'load_model': '../scGPT_human', 'mask_ratio': 0.0, 'epochs': 10, 'n_bins': 51, 'MVC': False, 'ecs_thres': 0.0, 'dab_weight': 0.0, 'lr': 0.0001, 'batch_size': 32, 'layer_size': 128, 'nlayers': 4, 'nhead': 4, 'dropout': 0.2, 'schedule_ratio': 0.9, 'save_eval_interval': 5, 'fast_transformer': True, 'pre_norm': False, 'amp': True, 'include_zero_gene': False, 'freeze': False, 'DSBN': False}
2025-03-14 22:38:12,519 INFO    MainThread:388287 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 8rw1zvm4
2025-03-14 22:38:12,521 INFO    MainThread:388287 [wandb_run.py:_finish():1970] finishing run dennis0628/scGPT/8rw1zvm4
2025-03-14 22:38:12,522 INFO    MainThread:388287 [jupyter.py:save_history():445] not saving jupyter history
2025-03-14 22:38:12,523 INFO    MainThread:388287 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2025-03-14 22:38:12,524 INFO    MainThread:388287 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2025-03-14 22:38:12,525 INFO    MainThread:388287 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2025-03-14 22:38:12,527 INFO    MainThread:388287 [wandb_run.py:_restore():2193] restore
2025-03-14 22:38:12,528 INFO    MainThread:388287 [wandb_run.py:_restore():2199] restore done
2025-03-14 22:38:17,779 INFO    MainThread:388287 [wandb_run.py:_footer_history_summary_info():3851] rendering history
2025-03-14 22:38:17,780 INFO    MainThread:388287 [wandb_run.py:_footer_history_summary_info():3883] rendering summary
2025-03-14 22:38:17,794 INFO    MainThread:388287 [wandb_run.py:_footer_sync_info():3810] logging synced files
2025-03-14 22:38:17,901 INFO    MainThread:388287 [wandb_init.py:init():616] starting backend
2025-03-14 22:38:17,901 INFO    MainThread:388287 [wandb_init.py:init():620] setting up manager
2025-03-14 22:38:17,905 INFO    MainThread:388287 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: fork
2025-03-14 22:38:17,907 INFO    MainThread:388287 [wandb_init.py:init():628] backend started and connected
2025-03-14 22:38:17,916 INFO    MainThread:388287 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2025-03-14 22:38:17,917 INFO    MainThread:388287 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-03-14 22:38:17,917 INFO    MainThread:388287 [wandb_init.py:init():720] updated telemetry
2025-03-14 22:38:18,089 INFO    MainThread:388287 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2025-03-14 22:38:19,188 INFO    MainThread:388287 [wandb_run.py:_on_init():2262] communicating current version
2025-03-14 22:38:19,224 INFO    MainThread:388287 [wandb_run.py:_on_init():2271] got version response upgrade_message: "wandb version 0.19.8 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-03-14 22:38:19,225 INFO    MainThread:388287 [wandb_init.py:init():804] starting run threads in backend
2025-03-14 22:38:34,073 INFO    MainThread:388287 [wandb_run.py:_console_start():2241] atexit reg
2025-03-14 22:38:34,074 INFO    MainThread:388287 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2025-03-14 22:38:34,075 INFO    MainThread:388287 [wandb_run.py:_redirect():2161] Wrapping output streams.
2025-03-14 22:38:34,075 INFO    MainThread:388287 [wandb_run.py:_redirect():2186] Redirects installed.
2025-03-14 22:38:34,077 INFO    MainThread:388287 [wandb_init.py:init():847] run started, returning control to user process
2025-03-14 22:39:27,704 INFO    MainThread:388287 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2025-03-14 22:39:27,706 INFO    MainThread:388287 [wandb_setup.py:_flush():76] Configure stats pid to 388287
2025-03-14 22:39:27,707 INFO    MainThread:388287 [wandb_setup.py:_flush():76] Loading settings from /home/dennis00/.config/wandb/settings
2025-03-14 22:39:27,709 INFO    MainThread:388287 [wandb_setup.py:_flush():76] Loading settings from /home/dennis00/cortexGPT/wandb/settings
2025-03-14 22:39:27,710 INFO    MainThread:388287 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-03-14 22:39:27,711 INFO    MainThread:388287 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-03-14 22:39:27,713 INFO    MainThread:388287 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2025-03-14 22:39:27,714 INFO    MainThread:388287 [wandb_init.py:_log_setup():526] Logging user logs to /home/dennis00/cortexGPT/wandb/run-20250314_223927-pjfneq2z/logs/debug.log
2025-03-14 22:39:27,716 INFO    MainThread:388287 [wandb_init.py:_log_setup():527] Logging internal logs to /home/dennis00/cortexGPT/wandb/run-20250314_223927-pjfneq2z/logs/debug-internal.log
2025-03-14 22:39:27,717 INFO    MainThread:388287 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fb0c5b9d0f0>
2025-03-14 22:39:27,718 INFO    MainThread:388287 [wandb_init.py:init():566] calling init triggers
2025-03-14 22:39:27,719 INFO    MainThread:388287 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'seed': 0, 'dataset_name': 'ms', 'do_train': True, 'load_model': '../scGPT_data/scGPT_human', 'mask_ratio': 0.0, 'epochs': 10, 'n_bins': 51, 'MVC': False, 'ecs_thres': 0.0, 'dab_weight': 0.0, 'lr': 0.0001, 'batch_size': 32, 'layer_size': 128, 'nlayers': 4, 'nhead': 4, 'dropout': 0.2, 'schedule_ratio': 0.9, 'save_eval_interval': 5, 'fast_transformer': True, 'pre_norm': False, 'amp': True, 'include_zero_gene': False, 'freeze': False, 'DSBN': False}
2025-03-14 22:39:27,721 INFO    MainThread:388287 [wandb_init.py:init():591] re-initializing run, found existing run on stack: ftth0b4x
2025-03-14 22:39:27,723 INFO    MainThread:388287 [wandb_run.py:_finish():1970] finishing run dennis0628/scGPT/ftth0b4x
2025-03-14 22:39:27,724 INFO    MainThread:388287 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2025-03-14 22:39:27,726 INFO    MainThread:388287 [wandb_run.py:_restore():2193] restore
2025-03-14 22:39:27,727 INFO    MainThread:388287 [wandb_run.py:_restore():2199] restore done
2025-03-14 22:39:32,190 INFO    MainThread:388287 [wandb_run.py:_footer_history_summary_info():3851] rendering history
2025-03-14 22:39:32,401 INFO    MainThread:388287 [wandb_run.py:_footer_history_summary_info():3883] rendering summary
2025-03-14 22:39:32,417 INFO    MainThread:388287 [wandb_run.py:_footer_sync_info():3810] logging synced files
